name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  checks: write
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup submodules
        run: git submodule update --init --recursive

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Setup apt packages
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends cmake llvm-dev clang libclang-dev

      - name: Check formatting
        run: cargo fmt  -- --check

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true

      # Format and Clippy steps are executed in separate 'check' workflow
      - name: Build
        run: cargo build --all-features --all --verbose

      - name: Run tests
        run: cargo test --all-features --verbose

  checks:
    name: Formatting checks and Clippy linter run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy, rustfmt

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Setup apt packages
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends cmake llvm-dev clang libclang-dev

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo +stable fmt  -- --check

      - name: Clippy
        run: cargo +stable clippy --tests --all-features -- -Dclippy::all

      - name: Docs
        env:
          RUSTDOCFLAGS: --cfg docsrs
        run: cargo +nightly doc --all-features
